// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBJww083EKMrnaJ9fsnHaZwKYqoMD8tM',
    appId: '1:720214528634:web:011a410196d0a8709361c3',
    messagingSenderId: '720214528634',
    projectId: 'zeno-staging',
    authDomain: 'zeno-staging.firebaseapp.com',
    storageBucket: 'zeno-staging.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-fmVYYhdAi1swV4ILkczAXHlS11X0nv0',
    appId: '1:720214528634:android:d95da2bf57d9e0189361c3',
    messagingSenderId: '720214528634',
    projectId: 'zeno-staging',
    storageBucket: 'zeno-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUlZiJLACP2p5yNR7cVWlA22oPxXDHyX4',
    appId: '1:720214528634:ios:3873e18553a89fbb9361c3',
    messagingSenderId: '720214528634',
    projectId: 'zeno-staging',
    storageBucket: 'zeno-staging.appspot.com',
    iosClientId: '720214528634-g6e5uhqjpqfvne3uv4gs812gim9datlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUlZiJLACP2p5yNR7cVWlA22oPxXDHyX4',
    appId: '1:720214528634:ios:3873e18553a89fbb9361c3',
    messagingSenderId: '720214528634',
    projectId: 'zeno-staging',
    storageBucket: 'zeno-staging.appspot.com',
    iosClientId: '720214528634-g6e5uhqjpqfvne3uv4gs812gim9datlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );
}
